#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 VERSION" >&2
  exit 1
fi

version=$1
sed -i -e "s/currentVersion = \"([0-9]+\.?)+\"/currentVersion = \"$version\"/" sensu/client.go
sed -i -e "s/download\/v([0-9]+\.?)+\/sensu-client-go-linux-amd64-([0-9]+\.?)+/download\/$version\/sensu-client-go-linux-amd64-$version/" README.md
sed -i -e "s/download\/v([0-9]+\.?)+\/sensu-client-go-darwin-amd64-([0-9]+\.?)+/download\/$version\/sensu-client-go-darwin-amd64-$version/" README.md

#git commit sensu/client.go README.md -m "Release $version"

#git tag v$version

#GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o sensu-client-go-linux-amd64-$version .
#GOOS=darwin CGO_ENABLED=0 GOARCH=amd64 go build -o sensu-client-go-darwin-amd64-$version .

#hub release create -a sensu-client-go-linux-amd64-$version -a sensu-client-go-darwin-amd64-$version v$version

#rm sensu-client-go-*
